name: Analyze Account Limit
on: [workflow_dispatch]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "START"
      - name: Download
        run: curl -sL -o /tmp/tf.zip "https://github.com/Linsars/lead/releases/download/ipa-telegram-12.8/Telegram.ipa"
      - run: ls -lh /tmp/tf.zip
